apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-service
  namespace: ordering
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: gcr.io/google-samples/microservices-demo/orderservice:v0.3.6
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: MISSING_CONFIG_MAP_REF
          valueFrom:
            configMapKeyRef:
              name: some-missing-config
              key: foo
        - name: MISSING_CONFIG_MAP_KEY_REF
          valueFrom:
            configMapKeyRef:
              name: test-config
              key: bar
        - name: GOOD_CONFIG_MAP_KEY_REF
          valueFrom:
            configMapKeyRef:
              name: test-config
              key: foo
        - name: OPTIONAL_MISSING_CONFIG_MAP_REF
          valueFrom:
            configMapKeyRef:
              name: some-missing-config
              key: foo
              optional: true
        - name: OPTIONAL_MISSING_CONFIG_MAP_KEY_REF
          valueFrom:
            configMapKeyRef:
              name: test-config
              key: bar
              optional: true
        - name: OPTIONAL_GOOD_CONFIG_MAP_KEY_REF
          valueFrom:
            configMapKeyRef:
              name: test-config
              key: foo
              optional: true
        envFrom:
        - configMapRef:
            name: test-config
        - configMapRef:
            name: some-missing-config
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        livenessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi