on: [push]

jobs:
  kubevious_validation:
    runs-on: ubuntu-latest
    name: Kubevious CLI Validation Run
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout Mock Repo
        uses: actions/checkout@v3        
        with:
          repository: kubevious/mock-data
          path: mock-data.git
      - name: 'Prepare Packages'
        run: './scripts/prepare-package.sh'
      - name: 'Build'
        run: 'docker build -t kubevious/cli .'
      - name: Validation of manifest files
        id: file-validation
        uses: kubevious/cli@main
        with:
          manifests: samples/argo-rollout
          crds: https://raw.githubusercontent.com/kubevious/demos/main/crds/argo-rollouts/crds.yaml        
      - name: Validation of Helm Charts
        id: chart-validation
        uses: kubevious/cli@main
        with:
          helm_repo_url: https://helm.kubevious.io
          helm_repo_name: kubevious
          helm_chart: kubevious
          helm_namespace: kubevious
          helm_include_crds: true